name: supabase ping

on:
  schedule:
    - cron: '0 0 */3 0 0' # 00:00 UTC every 3 days

  workflow_dispatch:
    # for manual testing


jobs:
  ping-server:
    runs-on: ubuntu-latest

    steps:
      - name: Send ping to Modal backend
        run: |
          curl -f -X GET "https://yammahtea--mediscan-backend-fastapi-app.modal.run/keep-alive" \
          -H "x-keep-alive-token: ${{ secrets.KEEP_ALIVE_TOKEN }}"